apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-admin-password
  namespace: cloudbees
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jenkins-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: cbci-lab/jenkins-admin-password
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: cbci-lab/grafana-admin-password
        property: password
    - secretKey: admin-user
      remoteRef:
        key: cbci-lab/grafana-admin-password
        property: username
