apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: citest-1-pdb
  namespace: ci-controllers
spec:
  minAvailable: 1
  selector:
    matchLabels:
      com.cloudbees.cje.tenant: citest-1
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: citest2-pdb
  namespace: ci-controllers
spec:
  minAvailable: 1
  selector:
    matchLabels:
      com.cloudbees.cje.tenant: citest2
