apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: controller-1-pdb
  namespace: ci-controllers
spec:
  minAvailable: 1
  selector:
    matchLabels:
      com.cloudbees.cje.tenant: controller-1
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: controller-2-pdb
  namespace: ci-controllers
spec:
  minAvailable: 1
  selector:
    matchLabels:
      com.cloudbees.cje.tenant: controller-2
