serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::835090871306:role/cbci-lab-eso"

# Run ESO on controller nodes
nodeSelector:
  role: controller

resources:
  requests:
    cpu: "100m"
    memory: 128Mi
  limits:
    cpu: "200m"
    memory: 256Mi
